appPython/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('web_app/', include('web_app.urls'))
]
#
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_app/urls.py
from django.urls import path

from . import views

app_name = 'web_app'

urlpatterns = [
    path('', views.ShowCategory.as_view(), name='category'),
    # path('product/', views.ShowProduct.as_view(), name='product'),
    path('<int:pk>/', views.DetailCategory.as_view(), name='detailCat'),
    path('detail/<int:pk>/', views.ProductDetail.as_view(), name='detail'),
    path('orders/create/', views.OrdersCreate.as_view(), name='create_order'),
    path('orders/update/<int:pk>/', views.OrdersCreate.as_view(), name='create_order'),


]

web_app/models.py
from django.db import models


class customers(models.Model):
    id = models.AutoField(primary_key=True)
    forename = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)
    add1 = models.CharField(max_length=100)
    add2 = models.CharField(max_length=100, blank=True, null=True)
    add3 = models.CharField(max_length=100, blank=True, null=True)
    postcode = models.IntegerField()
    email = models.EmailField(max_length=254)
    registered = models.BooleanField(default=False)

    def __str__(self):
        return '%s %s' % (self.surname, self.forename)


class logins(models.Model):
    id = models.AutoField(primary_key=True)
    customer_id = models.ForeignKey(customers, on_delete=models.CASCADE)
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)


class delivery_addresses(models.Model):
    id = models.AutoField(primary_key=True)
    forename = models.CharField(max_length=20)
    surname = models.CharField(max_length=20)
    add1 = models.CharField(max_length=100)
    add2 = models.CharField(max_length=100, blank=True, null=True)
    add3 = models.CharField(max_length=100, blank=True, null=True)
    postcode = models.IntegerField()
    phone = models.IntegerField()
    email = models.EmailField(max_length=254)


class orders(models.Model):
    id = models.AutoField(primary_key=True)
    customers_id = models.ForeignKey(customers, on_delete=models.CASCADE)
    registered = models.BooleanField(default=False)
    delivery_add_id = models.ForeignKey(delivery_addresses, on_delete=models.CASCADE)
    payment_type = models.CharField(max_length=20)
    date = models.DateTimeField('date order')
    status = models.BooleanField(default=False)
    session = models.CharField(max_length=20, blank=True, null=True)
    total = models.DecimalField(max_digits=12, decimal_places=0)


class categories(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.TextField()
    image = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class products(models.Model):
    id = models.AutoField(primary_key=True)
    cat_id = models.ForeignKey(categories, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=12, decimal_places=0)

    def __str__(self):
        return self.name


class order_items(models.Model):
    id = models.AutoField(primary_key=True)
    order_id = models.ForeignKey(orders, on_delete=models.CASCADE)
    product_id = models.ForeignKey(products, on_delete=models.CASCADE)
    quantity = models.IntegerField()

web_app/views.py
from django.views.generic import ListView, DetailView,CreateView
from django.urls import reverse_lazy
from . import models


class ShowProduct(ListView):
    template_name = 'web_app/product.html'
    queryset = models.products.objects.all()


class ProductDetail(DetailView):
    model = models.products
    template_name = 'web_app/detail.html'


class OrdersCreate(CreateView):
    model = models.orders
    fields = ['status', 'total']
    success_url = reverse_lazy('web_app:product')


class ShowCategory(ListView):
    template_name = 'web_app/category.html'
    queryset = models.categories.objects.all()


class DetailCategory(DetailView):
    template_name = 'web_app/detailCat.html'
    model = models.categories

web_app/templates/web_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>

{% block content %}

{% endblock %}

</body>
</html>

web_app/templates/web_app/category.html
{% extends './base.html' %}
{% block content %}
    {% if object_list %}
        <h2>List category</h2>
        <div style="padding-left:1rem">
            <ul>
                {% for categories in object_list %}
                    <li><a href="{% url 'web_app:detailCat' categories.id %}">{{ categories.name }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <p>No polls are available.</p>
        </div>
    {% endif %}
{% endblock %}

web_app/templates/web_app/detail.html
{% extends './base.html' %}
{% block content %}
<h2> Name: {{ object.name }}</h2>
<img src="{{ object.image }}" alt="my image">
<h3> Price: {{ object.price }} </h3>
<p> Description: {{ object.description }} </p>
{% endblock %}

web_app/templates/web_app/detailCat.html
{% extends './base.html' %}
{% block content %}
    {% if object.products_set %}
        <h2>List {{ categories.name }}</h2>
        <div style="padding-left:1rem">
            <ul>
                {% for products in object.products_set.all %}
                    <li><a href="{% url 'web_app:detail' products.id %}">{{ products.name }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <p>No polls are available.</p>
        </div>
    {% endif %}
{% endblock %}

web_app/templates/web_app/orders_form.html
{% extends './base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send message">
</form>
{% endblock %}

web_app/templates/web_app/product.html
{% extends './base.html' %}
{% block content %}
    {% if object_list %}
        <h2>List product</h2>
        <div style="padding-left:1rem">
            <ul>
                {% for products in object_list %}
                    <li><a href="{% url 'web_app:detail' products.id %}">{{ products.name }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <p>No polls are available.</p>
        </div>
    {% endif %}
{% endblock %}